# Generated by Django 3.1.2 on 2020-10-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_nombre', models.CharField(max_length=100)),
                ('curso_publicado', models.DateTimeField(verbose_name='Fecha de publicacion')),
            ],
        ),
    ]
